c_compiler_version:
  - 9.3

cxx_compiler_version:
  - 9.3

CFLAGS: >-
  -O2
  -fPIC
  -ffunction-sections
  -fno-plt
  -fstack-protector-strong
  -ftree-vectorize
  -march=x86-64
  -mtune=generic
  -pipe
