{% set version = "2.0.1" %}
{% set sha256 = "fdc95d4a632faf03697db8d8b2db92c7e5569926d374311acc1df20d1d1abbdc" %}

package:
  name: baton-pkg
  version: "{{ version }}"

about:
  home: https://github.com/wtsi-npg/baton
  license: GPL2
  summary: Client programs and API for use with iRODS (Integrated Rule-Oriented Data System).

build:
  number: 0

source:
  url: https://github.com/wtsi-npg/baton/releases/download/{{ version }}/baton-{{ version }}.tar.gz
  fn: baton-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("c") }}
    - autoconf
    - automake
    - libtool
    - make
    - perl
    - pkg-config
  host:
    - irods-dev ==4.1.12
    - libjansson-dev
    - libssl-dev
  run:
    - {{ pin_subpackage("libbaton", exact=True) }}
    - irods-plugins ==4.1.12
    - libjansson
    - libssl

outputs:
  - name: baton
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - autoconf
        - automake
        - libtool
        - make
        - perl
        - pkg-config
      host:
        - irods-dev ==4.1.12
        - libjansson-dev
        - libssl-dev
      run:
        - {{ pin_subpackage("libbaton", exact=True) }}
        - irods-plugins ==4.1.12
        - libjansson
        - libssl
    files:
      - bin/baton-*
    test:
      commands:
        - baton-list --version

  - name: libbaton
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - autoconf
        - automake
        - libtool
        - make
        - perl
        - pkg-config
      host:
        - irods-dev ==4.1.12
        - libjansson-dev
        - libssl-dev
      run:
        - irods-plugins ==4.1.12
        - libjansson
        - libssl
    files:
      - lib/libbaton.*
    test:
      commands:
        - test -h ${PREFIX}/lib/libbaton.so

  - name: libbaton-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libbaton", exact=True) }}
    files:
      - include/baton
      - lib/pkgconfig/baton.pc
    test:
      commands:
        - test -f ${PREFIX}/include/baton/baton.h
