{% set version = "2.3" %}

package:
  name: mash
  version: "{{ version }}"

about:
  home: http://mash.readthedocs.org
  license: Other
  summary: A fast sequence distance estimator using MinHash.

build:
  number: 0

source:
  git_url: https://github.com/marbl/Mash
  git_rev: v{{ version }}
  patches:
    - Makefile.in.patch

requirements:
  build:
    - {{ compiler("cxx") }}
    - autoconf
    - automake
    - libtool
    - make
  host:
    - boost
    - capnproto
    - libz-dev
  run:
    - boost
    - capnproto
    - libz

test:
  commands:
    - mash -h
