{% set version = "1.1.0_3_gbde56b5" %}

package:
  name: qcat
  version: "{{ version }}"

build:
  number: 0

source:
  git_url: https://github.com/kjsanger/qcat
  git_rev: "v1.1.0-3-gbde56b5"

requirements:
  host:
    - python
    - pip
    - biopython
    - parasail-python
    - pyyaml
    - six
  run:
    - python
    - biopython
    - parasail-python
    - pyyaml
    - six

test:
  commands:
    - qcat -h

about:
  home: https://github.com/nanoporetech/qcat
  summary: |
    qcat is a Python command-line tool for demultiplexing Oxford
    Nanopore reads from FASTQ files.
