{% set version = "1.15.0" %} # reset build to zero on changing
{% set upstream_version = "1.15" %}
{% set htslib_version = "1.15.0" %}  # Bump build version on change
{% set sha256 = "1885ccb450a86e97a00aa905d7381ca9e07bd8967c05705a61d0007d2e22296e" %}

package:
  name: bcftools
  version: "{{ version }}"

about:
  home: https://github.com/samtools/bcftools
  license: MIT
  summary: VCF commands and BCF calling.

build:
  number: 0

source:
  url: https://github.com/samtools/bcftools/releases/download/{{ upstream_version }}/bcftools-{{ upstream_version }}.tar.bz2
  fn: bcftools-{{ upstream_version }}.tar.bz2
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("c") }}
    - make
  host:
    - libhts-dev =={{ htslib_version }}
    - libz-dev
  run:
    - libhts =={{ htslib_version }}
    - libz

test:
  commands:
    - bcftools --help
