{% set version = "v2.0pre1_25_g1038fe3" %}
{% set bwa_mem2_rev = "1038fe3b701cb6cd6e8c10a5ffbfdf5512167da2" %}

package:
  name: bwa-mem2
  version: "{{ version }}"

about:
  home: https://github.com/bwa-mem2/bwa-mem2
  license: MIT
  summary: Burrows-Wheeler Aligner for short-read alignment.

build:
  number: 2

source:
  - git_url: https://github.com/bwa-mem2/bwa-mem2.git
    git_rev: "{{bwa_mem2_rev }}"

    patches:
      - Makefile.patch

requirements:
  build:
    - {{ compiler("cxx") }}
    - make
  host:
    - libz-dev
  run:
    - libz

test:
  commands:
    - test -x ${PREFIX}/bin/bwa-mem2
