{% set version = "0.23.3" %}
{% set sha256 = "af8d1e74e6ab67c652ede8e1ef7da89cf435ca3363ca50df5ff472fddd19a206" %}

package:
  name: wr
  version: "{{ version }}"

about:
  home: https://github.com/VertebrateResequencing/wr
  license: GPL3
  summary: "High performance Workflow Runner."

build:
  number: 0
  binary_relocation: false

source:
  url: https://github.com/VertebrateResequencing/wr/releases/download/v{{ version }}/wr-linux-x86-64.zip
  fn: wr-{{ version }}.zip
  sha256: {{ sha256 }}

test:
  commands:
    - wr -h
