{% set version = "2.1.0" %}
{% set shortver = "210" %}
{% set sha256 = "89a276eed1fc07414b1601947bc9466bdeb50e8f148ad42074186fe39a1ee781" %}

package:
  name: hisat2
  version: "{{ version }}"

about:
  home: http://ccb.jhu.edu/software/hisat2/index.shtml
  license: GPL3
  summary: "Graph-based alignment of next generation sequencing reads to a population of genomes."

build:
  number: 3

source:
  url: "https://cloud.biohpc.swmed.edu/index.php/s/hisat2-{{ shortver }}-source/download"
  fn: hisat2-{{ shortver }}-source.zip
  sha256: {{ sha256 }}
  patches:
    - Makefile.patch

requirements:
  build:
    - {{ compiler("cxx") }}
    - make
  host:
    - libz-dev
  run:
    - libz

test:
  commands:
    - hisat2 -h
    - hisat2 --version | grep -qP '\b\Q{{ version }}\E\b'
