{% set version = "0.1.0" %}

package:
  name: ml-warehouse
  version: "{{ version }}"

about:
  home: https://github.com/wtsi-npg/ml-warehouse-python
  license: GPL3
  summary: "Python SQLAlchemy bindings to a warehouse housing data from multiple LIM systems."

build:
  number: 0

source:
  git_url: https://github.com/wtsi-npg/ml-warehouse-python.git
  git_rev: "{{ version }}"

requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - cryptography >=3.4.8,<3.5
    - pymysql >=1.0.2,<1.1
    - sqlalchemy-utils >=0.37.8,<0.38
    - sqlalchemy >=1.4

test:
  imports:
    - ml_warehouse

about:
  home: https://github.com/wtsi-npg/ml-warehouse-python
