{% set version = "3.9.1" %}
{% set sha256 = "4cf0df69731494668bdd6460ed8cb269b68de9c19ad8c27abc24cd72605b2d5b" %}

package:
  name: json
  version: "{{ version }}"

about:
  home: https://json.nlohmann.me/
  license: MIT
  summary: "JSON for Modern C++ is a C++11 JSON parser"

source:
  url: https://github.com/nlohmann/json/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

files:
  - include/nlohmann/
  - lib/pkgconfig/nlohmann_json.pc
  - lib/cmake/nlohmann_json/

test:
  commands:
    - test -f ${PREFIX}/include/nlohmann/json.hpp
