{% set version = "1.3" %} # reset build to zero on changing
{% set seqtk_rev = "fe1cc9e8d926d40a88f6ff368c07466d33c3665d" %}

package:
  name: seqtk
  version: "{{ version }}"

about:
  home: https://github.com/lh3/seqtk
  license: MIT
  summary: "A fast and lightweight tool for processing sequences in the FASTA or FASTQ format."

build:
  number: 0

source:
  - git_url: https://github.com/lh3/seqtk.git
    git_rev: {{ seqtk_rev }}

requirements:
  build:
    - {{ compiler("c") }}
    - make
  host:
    - libz-dev
  run:
    - libz

outputs:
  - name: seqtk
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - make
      host:
        - libz-dev
      run:
        - libz
    files:
      - bin/seqtk

test:
  commands:
    - test -x ${PREFIX}/bin/seqtk
    - echo -e ">foo\nACGTTTT\n" | seqtk seq -r -
    - seqtk 2>&1 | grep -qP '\Q{{ version }}\E\b'
